### ISSUE TITLE
无法通过配置项取消自动保存

### ISSUE THREAD

**Issue by Roamin** [ct-adc/ct-adc-ueditor#2]
按照百度官方文档，设置 `enableAutoSave:  false` 应该就能取消自动保存，然而实际无效。搜索一堆，还要改官方源码。

**Comment by Roamin** [comment]
目前仅视觉上禁掉保存提示的方式，设置 CSS：
```css
/* 禁掉自动保存提示 */
.edui-default .edui-editor-messageholder {
    display: none!important;
}
```
